In [ ]:
pip install gensim

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 5.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 749.7 kB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.7/26.7 MB 84.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.3/18.3 MB 110.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.6/38.6 MB 14.5 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
  Attempting uninstall: scipy
    Found existing installation: scipy 1.15.3
    Uninstalling scipy-1.15.3:
      Successfully uninstalled scipy-1.15.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tsfresh 0.21.0 requires scipy>=1.14.0; python_version >= "3.10", but you have scipy 1.13.1 which is incompatible.
thinc 8.3.6 r

In [ ]:
pip install gensim==4.3.3 numpy==1.24.3 scipy==1.10.1

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.9/58.9 kB 5.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.7/26.7 MB 57.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 54.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 34.1/34.1 MB 13.5 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
  Attempting uninstall: scipy
    Found existing installation: scipy 1.15.3
    Uninstalling scipy-1.15.3:
      Successfully uninstalled scipy-1.15.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
jax 0.5.2 requires numpy>=1.25, but you have numpy 1.24.3 which is incompatible.
jax 0.5.2 requires scipy>=1.11.1, but you have scipy 1.10.1 which is incompatible.
tsfresh 0.21.0 requires scipy>=1.14.0; python

### Loading the Word2Vec Model

In [ ]:
from gensim.models import Word2Vec

model = Word2Vec.load('/content/youtube_word2vec_200dim.model')
print("Word2Vec model loaded successfully!")

Word2Vec model loaded successfully!


### Loading the Tokenized excel file

In [ ]:
import pandas as pd
import ast
# Load dataset
df = pd.read_excel("/content/sentiment_tokens.xlsx")

# Safe parsing: Convert stringified list to actual list
def safe_parse(x):
    try:
        return ast.literal_eval(x)
    except Exception as e:
        print(f"Error parsing row: {x[:80]}... -> {e}")
        return []

df['tokens'] = df['tokens'].apply(safe_parse)



Error parsing row: ['sidney', 'powel', 'credible', 'rolling_on_the_floor_laughing', 'rolling_on_the... -> '[' was never closed (<unknown>, line 1)
Error parsing row: ['relateable', 'party_popper', 'party_popper', 'party_popper', 'party_popper', '... -> '[' was never closed (<unknown>, line 1)


In [ ]:
df.shape

(963055, 2)

In [ ]:
print(df['tokens'].iloc[0])
print(type(df['tokens'].iloc[0]))  # Should now be <class 'list'>

['anyone', 'know', 'movie', '?']
<class 'list'>


### Create Sentence Embeddings (Mean Pooling)

In [ ]:
# BLOCK 3: Create Sentence Embeddings (Mean Pooling)

import numpy as np
from tqdm import tqdm

def sentence_embedding(tokens, model):
    vectors = [model[word] for word in tokens if word in model]
    if not vectors:
        return np.zeros(model.vector_size)
    return np.mean(vectors, axis=0)

# Build feature matrix X
X = np.array([sentence_embedding(tokens, model.wv) for tokens in tqdm(df['tokens'])])


100%|██████████| 963055/963055 [00:46<00:00, 20884.72it/s]


In [ ]:
X

array([[-0.140857  , -0.03284824, -0.06331647, ..., -0.17949659,
        -0.12216   , -0.14116634],
       [ 0.04501991,  0.01944968,  0.2220042 , ..., -0.11654779,
         0.0016356 ,  0.05193744],
       [ 0.07193813,  0.07645284, -0.25776291, ..., -0.05467423,
         0.0794609 , -0.17267951],
       ...,
       [-0.0154625 ,  0.11621616,  0.0079456 , ..., -0.12408878,
         0.07909657,  0.13012357],
       [ 0.02637978,  0.01195572,  0.09002316, ..., -0.19372623,
         0.01496309,  0.01822849],
       [-0.17009021,  0.01112945, -0.27889833, ..., -0.32648149,
         0.15604128,  0.17522995]])

In [ ]:
df.columns

Index(['Sentiment', 'tokens'], dtype='object')

In [ ]:
y = df['Sentiment'].values

In [ ]:
y

array(['Neutral', 'Positive', 'Neutral', ..., 'Negative', 'Neutral',
       'Neutral'], dtype=object)

In [ ]:
# BLOCK 4: Encode Labels & Train-Test Split
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

X_train, X_test, y_train, y_test = train_test_split(
    X, y_encoded, test_size=0.2, random_state=42, stratify=y_encoded
)

print(f"Classes: {label_encoder.classes_}")


Classes: ['Negative' 'Neutral' 'Positive']


In [ ]:
y_encoded

array([1, 2, 1, ..., 0, 1, 1])

### Traning the Sentence Embedding created on ML models

#### Deafult Logistic Regression Accuracy

In [ ]:
#  BLOCK 5: Train Models & Evaluate


In [ ]:
#  Logistic Regression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

log_reg = LogisticRegression(max_iter=1000)
log_reg.fit(X_train, y_train)
y_pred_log = log_reg.predict(X_test)

print("=== Logistic Regression ===")
print("Accuracy:", accuracy_score(y_test, y_pred_log))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_log))
print("Classification Report:\n", classification_report(y_test, y_pred_log, target_names=label_encoder.classes_))


=== Logistic Regression ===
Accuracy: 0.6603361178748878
Confusion Matrix:
 [[45173 14055  5960]
 [15940 36136 10055]
 [ 9113 10300 45879]]
Classification Report:
               precision    recall  f1-score   support

    Negative       0.64      0.69      0.67     65188
     Neutral       0.60      0.58      0.59     62131
    Positive       0.74      0.70      0.72     65292

    accuracy                           0.66    192611
   macro avg       0.66      0.66      0.66    192611
weighted avg       0.66      0.66      0.66    192611



#### Default Random Forest Accuracy

In [ ]:
# Random Forest
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)

print("=== Random Forest ===")
print("Accuracy:", accuracy_score(y_test, y_pred_rf))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_rf))
print("Classification Report:\n", classification_report(y_test, y_pred_rf, target_names=label_encoder.classes_))


KeyboardInterrupt: 

#### Default Xgboost Accuracy

In [ ]:
# XGBoostXG
import xgboost as xgb

xgb_model = xgb.XGBClassifier(
    objective='multi:softmax', num_class=len(label_encoder.classes_),
    eval_metric='mlogloss', use_label_encoder=False
)
xgb_model.fit(X_train, y_train)
y_pred_xgb = xgb_model.predict(X_test)

print("=== XGBoost ===")
print("Accuracy:", accuracy_score(y_test, y_pred_xgb))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_xgb))
print("Classification Report:\n", classification_report(y_test, y_pred_xgb, target_names=label_encoder.classes_))


/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [19:06:53] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


=== XGBoost ===
Accuracy: 0.6852256620857583
Confusion Matrix:
 [[47566 12287  5335]
 [15458 37879  8794]
 [ 9348  9407 46537]]
Classification Report:
               precision    recall  f1-score   support

    Negative       0.66      0.73      0.69     65188
     Neutral       0.64      0.61      0.62     62131
    Positive       0.77      0.71      0.74     65292

    accuracy                           0.69    192611
   macro avg       0.69      0.68      0.68    192611
weighted avg       0.69      0.69      0.69    192611



#### Default LightGBM Accuracy

In [ ]:
# LightGBM
import lightgbm as lgb

lgb_model = lgb.LGBMClassifier(objective='multiclass', num_class=len(label_encoder.classes_))
lgb_model.fit(X_train, y_train)
y_pred_lgb = lgb_model.predict(X_test)

print("=== LightGBM ===")
print("Accuracy:", accuracy_score(y_test, y_pred_lgb))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_lgb))
print("Classification Report:\n", classification_report(y_test, y_pred_lgb, target_names=label_encoder.classes_))


/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 3.236304 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 51000
[LightGBM] [Info] Number of data points in the train set: 770444, number of used features: 200
[LightGBM] [Info] Start training from score -1.083397
[LightGBM] [Info] Start training from score -1.131428
[LightGBM] [Info] Start training from score -1.081803


/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


=== LightGBM ===
Accuracy: 0.6715296634148621
Confusion Matrix:
 [[46826 13101  5261]
 [16248 37293  8590]
 [10045 10022 45225]]
Classification Report:
               precision    recall  f1-score   support

    Negative       0.64      0.72      0.68     65188
     Neutral       0.62      0.60      0.61     62131
    Positive       0.77      0.69      0.73     65292

    accuracy                           0.67    192611
   macro avg       0.67      0.67      0.67    192611
weighted avg       0.68      0.67      0.67    192611



In [ ]:
# === XGBoost (GPU) ===
print("\n=== XGBoost (GPU) ===")
xgb_model = xgb.XGBClassifier(
    tree_method='gpu_hist',
    predictor='gpu_predictor',
    max_depth=10,
    n_estimators=100,
    random_state=42,
    verbosity=1,
)
xgb_model.fit(X_train, y_train)
y_pred_xgb = xgb_model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred_xgb))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_xgb))
print("Classification Report:\n", classification_report(y_test, y_pred_xgb, target_names=label_encoder.classes_))


=== XGBoost (GPU) ===


/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [19:22:12] WARNING: /workspace/src/common/error_msg.cc:27: The tree method `gpu_hist` is deprecated since 2.0.0. To use GPU training, set the `device` parameter to CUDA instead.

    E.g. tree_method = "hist", device = "cuda"

  warnings.warn(smsg, UserWarning)
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [19:22:12] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "predictor" } are not used.

  warnings.warn(smsg, UserWarning)
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [19:22:55] WARNING: /workspace/src/common/error_msg.cc:27: The tree method `gpu_hist` is deprecated since 2.0.0. To use GPU training, set the `device` parameter to CUDA instead.

    E.g. tree_method = "hist", device = "cuda"

  warnings.warn(smsg, UserWarning)
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [19:22:55] WARNING: /workspace/src/common/error_ms

Accuracy: 0.6961025071257613
Confusion Matrix:
 [[48031 12098  5059]
 [14569 39126  8436]
 [ 8786  9586 46920]]
Classification Report:
               precision    recall  f1-score   support

    Negative       0.67      0.74      0.70     65188
     Neutral       0.64      0.63      0.64     62131
    Positive       0.78      0.72      0.75     65292

    accuracy                           0.70    192611
   macro avg       0.70      0.70      0.70    192611
weighted avg       0.70      0.70      0.70    192611



In [ ]:
# === LightGBM (GPU optional) ===
print("\n=== LightGBM ===")
lgbm_model = lgb.LGBMClassifier(
    device='gpu',     # Remove this line if using CPU
    max_depth=10,
    num_leaves=31,
    n_estimators=100,
    random_state=42
)
lgbm_model.fit(X_train, y_train)
y_pred_lgb = lgbm_model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred_lgb))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_lgb))
print("Classification Report:\n", classification_report(y_test, y_pred_lgb, target_names=label_encoder.classes_))


=== LightGBM ===


/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


[LightGBM] [Info] This is the GPU trainer!!
[LightGBM] [Info] Total Bins 51000
[LightGBM] [Info] Number of data points in the train set: 770444, number of used features: 200
[LightGBM] [Info] Using GPU Device: Tesla T4, Vendor: NVIDIA Corporation
[LightGBM] [Info] Compiling OpenCL Kernel with 256 bins...
[LightGBM] [Info] GPU programs have been built
[LightGBM] [Info] Size of histogram bin entry: 8
[LightGBM] [Info] 200 dense feature groups (146.95 MB) transferred to GPU in 0.207184 secs. 0 sparse feature groups
[LightGBM] [Info] Start training from score -1.083397
[LightGBM] [Info] Start training from score -1.131428
[LightGBM] [Info] Start training from score -1.081803


/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


Accuracy: 0.6713323745788143
Confusion Matrix:
 [[46750 13218  5220]
 [16224 37301  8606]
 [ 9993 10044 45255]]
Classification Report:
               precision    recall  f1-score   support

    Negative       0.64      0.72      0.68     65188
     Neutral       0.62      0.60      0.61     62131
    Positive       0.77      0.69      0.73     65292

    accuracy                           0.67    192611
   macro avg       0.67      0.67      0.67    192611
weighted avg       0.68      0.67      0.67    192611



In [ ]:
# === Logistic Regression ===
print("\n=== Logistic Regression ===")
logreg = LogisticRegression(max_iter=1000, random_state=42)
logreg.fit(X_train, y_train)
y_pred_lr = logreg.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred_lr))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_lr))
print("Classification Report:\n", classification_report(y_test, y_pred_lr, target_names=label_encoder.classes_))


=== Logistic Regression ===
Accuracy: 0.6603361178748878
Confusion Matrix:
 [[45173 14055  5960]
 [15940 36136 10055]
 [ 9113 10300 45879]]
Classification Report:
               precision    recall  f1-score   support

    Negative       0.64      0.69      0.67     65188
     Neutral       0.60      0.58      0.59     62131
    Positive       0.74      0.70      0.72     65292

    accuracy                           0.66    192611
   macro avg       0.66      0.66      0.66    192611
weighted avg       0.66      0.66      0.66    192611



### LightGBM and Xgboost for Deeper Hyper-parameter Tuning

### Hyper-parameter tuning via Optuna

In [ ]:
pip install optuna lightgbm xgboost


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 386.6/386.6 kB 25.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 242.5/242.5 kB 23.2 MB/s eta 0:00:00


In [ ]:
import optuna
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
import lightgbm as lgb
import xgboost as xgb


In [ ]:
X_train, X_val, y_train, y_val = train_test_split(X, y_encoded, test_size=0.2, stratify=y, random_state=42)


In [ ]:
X_train.shape, X_val.shape, y_train.shape, y_val.shape

((770444, 200), (192611, 200), (770444,), (192611,))

In [ ]:
y_train

array([2, 2, 1, ..., 1, 0, 0])

### LightGBM hyper-parameter tuning

In [ ]:
import lightgbm as lgb
from lightgbm import early_stopping, log_evaluation
import xgboost as xgb
import optuna
from sklearn.metrics import accuracy_score
import joblib
import numpy as np


In [ ]:

# Make sure y, X_train, X_val, y_train, y_val are defined

# -------------------------------
# LIGHTGBM OPTUNA TUNING + SAVE
# -------------------------------
def objective_lgb(trial):
    param = {
        'objective': 'multiclass',
        'metric': 'multi_logloss',
        'boosting_type': 'gbdt',
        'num_class': len(set(y)),
        'verbosity': -1,
        'device': 'gpu',
        'gpu_platform_id': 0,
        'gpu_device_id': 0,
        'learning_rate': trial.suggest_float('learning_rate', 1e-3, 0.3, log=True),
        'num_leaves': trial.suggest_int('num_leaves', 31, 256),
        'max_depth': trial.suggest_int('max_depth', 4, 16),
        'min_child_samples': trial.suggest_int('min_child_samples', 10, 100),
        'subsample': trial.suggest_float('subsample', 0.5, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.5, 1.0),
        'reg_alpha': trial.suggest_float('reg_alpha', 1e-8, 10.0, log=True),
        'reg_lambda': trial.suggest_float('reg_lambda', 1e-8, 10.0, log=True)
    }

    train_set = lgb.Dataset(X_train, label=y_train)
    val_set = lgb.Dataset(X_val, label=y_val)

    model = lgb.train(
        param,
        train_set,
        valid_sets=[val_set],
        callbacks=[
            early_stopping(stopping_rounds=50),
            log_evaluation(period=10)
        ]
    )

    preds = model.predict(X_val)
    pred_labels = preds.argmax(axis=1)
    return accuracy_score(y_val, pred_labels)

# Run LightGBM tuning
study_lgb = optuna.create_study(direction='maximize')
study_lgb.optimize(objective_lgb, n_trials=50)
print("✅ Best LightGBM params:", study_lgb.best_params)

# Train final LightGBM model with best params
best_params_lgb = study_lgb.best_params
best_params_lgb.update({
    'objective': 'multiclass',
    'metric': 'multi_logloss',
    'boosting_type': 'gbdt',
    'num_class': len(set(y)),
    'verbosity': -1,
    'device': 'gpu',
    'gpu_platform_id': 0,
    'gpu_device_id': 0
})

train_set = lgb.Dataset(X_train, label=y_train)
val_set = lgb.Dataset(X_val, label=y_val)

final_lgb = lgb.train(
    best_params_lgb,
    train_set,
    valid_sets=[val_set],
    callbacks=[
        early_stopping(stopping_rounds=50),
        log_evaluation(period=10)
    ]
)

# Save final LightGBM model
joblib.dump(final_lgb, 'best_lightgbm.pkl')
print("✅ LightGBM model saved to best_lightgbm.pkl")

[I 2025-05-22 14:52:32,134] A new study created in memory with name: no-name-40e4a345-e895-4afb-8d6c-b5952470ffba


Training until validation scores don't improve for 50 rounds
[10]	valid_0's multi_logloss: 0.817268
[20]	valid_0's multi_logloss: 0.775915
[30]	valid_0's multi_logloss: 0.757608
[40]	valid_0's multi_logloss: 0.746918
[50]	valid_0's multi_logloss: 0.739437
[60]	valid_0's multi_logloss: 0.733955
[70]	valid_0's multi_logloss: 0.729262
[80]	valid_0's multi_logloss: 0.725492
[90]	valid_0's multi_logloss: 0.722441
[100]	valid_0's multi_logloss: 0.720059
Did not meet early stopping. Best iteration is:
[100]	valid_0's multi_logloss: 0.720059


[I 2025-05-22 14:53:45,995] Trial 0 finished with value: 0.6816588876024734 and parameters: {'learning_rate': 0.2974076182133885, 'num_leaves': 49, 'max_depth': 5, 'min_child_samples': 86, 'subsample': 0.7605254586821979, 'colsample_bytree': 0.5575807832927954, 'reg_alpha': 0.012893076468883968, 'reg_lambda': 0.17026608359845577}. Best is trial 0 with value: 0.6816588876024734.


Training until validation scores don't improve for 50 rounds
[10]	valid_0's multi_logloss: 0.974519
[20]	valid_0's multi_logloss: 0.904064
[30]	valid_0's multi_logloss: 0.859508
[40]	valid_0's multi_logloss: 0.829644
[50]	valid_0's multi_logloss: 0.808655
[60]	valid_0's multi_logloss: 0.793129
[70]	valid_0's multi_logloss: 0.781096
[80]	valid_0's multi_logloss: 0.771485
[90]	valid_0's multi_logloss: 0.763596
[100]	valid_0's multi_logloss: 0.756956
Did not meet early stopping. Best iteration is:
[100]	valid_0's multi_logloss: 0.756956


[I 2025-05-22 14:55:33,544] Trial 1 finished with value: 0.66771368198078 and parameters: {'learning_rate': 0.039771130450381234, 'num_leaves': 177, 'max_depth': 8, 'min_child_samples': 66, 'subsample': 0.8909021176741665, 'colsample_bytree': 0.6671628852333613, 'reg_alpha': 1.8484405828483973e-08, 'reg_lambda': 1.5969120042800658e-07}. Best is trial 0 with value: 0.6816588876024734.


Training until validation scores don't improve for 50 rounds
[10]	valid_0's multi_logloss: 1.03953
[20]	valid_0's multi_logloss: 0.995125
[30]	valid_0's multi_logloss: 0.960412
[40]	valid_0's multi_logloss: 0.932657
[50]	valid_0's multi_logloss: 0.909992
[60]	valid_0's multi_logloss: 0.891333
[70]	valid_0's multi_logloss: 0.875787
[80]	valid_0's multi_logloss: 0.862614
[90]	valid_0's multi_logloss: 0.851188
[100]	valid_0's multi_logloss: 0.841344
Did not meet early stopping. Best iteration is:
[100]	valid_0's multi_logloss: 0.841344


[I 2025-05-22 14:56:45,683] Trial 2 finished with value: 0.6386447295325812 and parameters: {'learning_rate': 0.01793833558648358, 'num_leaves': 253, 'max_depth': 6, 'min_child_samples': 87, 'subsample': 0.9552928206157524, 'colsample_bytree': 0.8763928694746412, 'reg_alpha': 5.026932232227248e-06, 'reg_lambda': 8.760561802633928}. Best is trial 0 with value: 0.6816588876024734.


Training until validation scores don't improve for 50 rounds
[10]	valid_0's multi_logloss: 1.08933
[20]	valid_0's multi_logloss: 1.08074
[30]	valid_0's multi_logloss: 1.07246
[40]	valid_0's multi_logloss: 1.06444
[50]	valid_0's multi_logloss: 1.05671
[60]	valid_0's multi_logloss: 1.0492
[70]	valid_0's multi_logloss: 1.04191
[80]	valid_0's multi_logloss: 1.0349
[90]	valid_0's multi_logloss: 1.02808
[100]	valid_0's multi_logloss: 1.02154
Did not meet early stopping. Best iteration is:
[100]	valid_0's multi_logloss: 1.02154


[I 2025-05-22 14:58:41,169] Trial 3 finished with value: 0.6254834874436039 and parameters: {'learning_rate': 0.0022270107527222706, 'num_leaves': 128, 'max_depth': 13, 'min_child_samples': 61, 'subsample': 0.8577474819916142, 'colsample_bytree': 0.7418048429012501, 'reg_alpha': 0.00024357869003356305, 'reg_lambda': 0.002095914650153677}. Best is trial 0 with value: 0.6816588876024734.


Training until validation scores don't improve for 50 rounds
[10]	valid_0's multi_logloss: 0.820515
[20]	valid_0's multi_logloss: 0.774132
[30]	valid_0's multi_logloss: 0.75344
[40]	valid_0's multi_logloss: 0.741563
[50]	valid_0's multi_logloss: 0.733442
[60]	valid_0's multi_logloss: 0.727089
[70]	valid_0's multi_logloss: 0.722426
[80]	valid_0's multi_logloss: 0.718641
[90]	valid_0's multi_logloss: 0.715452
[100]	valid_0's multi_logloss: 0.712797
Did not meet early stopping. Best iteration is:
[100]	valid_0's multi_logloss: 0.712797


[I 2025-05-22 14:59:49,505] Trial 4 finished with value: 0.6852568129546079 and parameters: {'learning_rate': 0.22519156543097418, 'num_leaves': 218, 'max_depth': 6, 'min_child_samples': 14, 'subsample': 0.5524018297578352, 'colsample_bytree': 0.8481135897435945, 'reg_alpha': 0.0007848821361461149, 'reg_lambda': 0.009221619998084542}. Best is trial 4 with value: 0.6852568129546079.


Training until validation scores don't improve for 50 rounds
[10]	valid_0's multi_logloss: 1.03996
[20]	valid_0's multi_logloss: 0.995537
[30]	valid_0's multi_logloss: 0.96022
[40]	valid_0's multi_logloss: 0.931742
[50]	valid_0's multi_logloss: 0.908536
[60]	valid_0's multi_logloss: 0.889219
[70]	valid_0's multi_logloss: 0.873074
[80]	valid_0's multi_logloss: 0.859444
[90]	valid_0's multi_logloss: 0.847741
[100]	valid_0's multi_logloss: 0.83762
Did not meet early stopping. Best iteration is:
[100]	valid_0's multi_logloss: 0.83762


[I 2025-05-22 15:01:14,510] Trial 5 finished with value: 0.6423828337945392 and parameters: {'learning_rate': 0.01755154804315452, 'num_leaves': 61, 'max_depth': 14, 'min_child_samples': 66, 'subsample': 0.9171881925151886, 'colsample_bytree': 0.7303290866680088, 'reg_alpha': 0.00991100395332814, 'reg_lambda': 0.0002595804215802485}. Best is trial 4 with value: 0.6852568129546079.


Training until validation scores don't improve for 50 rounds
[10]	valid_0's multi_logloss: 1.08765
[20]	valid_0's multi_logloss: 1.07752
[30]	valid_0's multi_logloss: 1.06778
[40]	valid_0's multi_logloss: 1.05841
[50]	valid_0's multi_logloss: 1.04943
[60]	valid_0's multi_logloss: 1.04075
[70]	valid_0's multi_logloss: 1.03238
[80]	valid_0's multi_logloss: 1.02434
[90]	valid_0's multi_logloss: 1.01657
[100]	valid_0's multi_logloss: 1.00914
Did not meet early stopping. Best iteration is:
[100]	valid_0's multi_logloss: 1.00914


[I 2025-05-22 15:03:47,148] Trial 6 finished with value: 0.6342887997051051 and parameters: {'learning_rate': 0.002507554890391266, 'num_leaves': 231, 'max_depth': 10, 'min_child_samples': 72, 'subsample': 0.5558120376316456, 'colsample_bytree': 0.7500361806305476, 'reg_alpha': 0.00040234980606156784, 'reg_lambda': 0.14314256298646238}. Best is trial 4 with value: 0.6852568129546079.


Training until validation scores don't improve for 50 rounds
[10]	valid_0's multi_logloss: 1.03865
[20]	valid_0's multi_logloss: 0.992199
[30]	valid_0's multi_logloss: 0.95533
[40]	valid_0's multi_logloss: 0.925422
[50]	valid_0's multi_logloss: 0.900922
[60]	valid_0's multi_logloss: 0.880554
[70]	valid_0's multi_logloss: 0.863523
[80]	valid_0's multi_logloss: 0.849221
[90]	valid_0's multi_logloss: 0.836885
[100]	valid_0's multi_logloss: 0.826345
Did not meet early stopping. Best iteration is:
[100]	valid_0's multi_logloss: 0.826345


[I 2025-05-22 15:05:30,193] Trial 7 finished with value: 0.6520759458182555 and parameters: {'learning_rate': 0.017147240997873476, 'num_leaves': 133, 'max_depth': 9, 'min_child_samples': 48, 'subsample': 0.912968146591841, 'colsample_bytree': 0.5190607138261798, 'reg_alpha': 0.0002762078322943501, 'reg_lambda': 1.0913949419292122}. Best is trial 4 with value: 0.6852568129546079.


Training until validation scores don't improve for 50 rounds
[10]	valid_0's multi_logloss: 0.944238
[20]	valid_0's multi_logloss: 0.879946
[30]	valid_0's multi_logloss: 0.845334
[40]	valid_0's multi_logloss: 0.823271
[50]	valid_0's multi_logloss: 0.808132
[60]	valid_0's multi_logloss: 0.796943
[70]	valid_0's multi_logloss: 0.788023
[80]	valid_0's multi_logloss: 0.780918
[90]	valid_0's multi_logloss: 0.774884
[100]	valid_0's multi_logloss: 0.76988
Did not meet early stopping. Best iteration is:
[100]	valid_0's multi_logloss: 0.76988


[I 2025-05-22 15:06:20,453] Trial 8 finished with value: 0.6586799300143813 and parameters: {'learning_rate': 0.08302557510458468, 'num_leaves': 236, 'max_depth': 4, 'min_child_samples': 53, 'subsample': 0.9612771248569068, 'colsample_bytree': 0.7037616623578666, 'reg_alpha': 1.4070287348982518e-08, 'reg_lambda': 3.3498310613951356}. Best is trial 4 with value: 0.6852568129546079.


Training until validation scores don't improve for 50 rounds
[10]	valid_0's multi_logloss: 1.03623
[20]	valid_0's multi_logloss: 0.988857
[30]	valid_0's multi_logloss: 0.95143
[40]	valid_0's multi_logloss: 0.92126
[50]	valid_0's multi_logloss: 0.896667
[60]	valid_0's multi_logloss: 0.876148
[70]	valid_0's multi_logloss: 0.858993
[80]	valid_0's multi_logloss: 0.844416
[90]	valid_0's multi_logloss: 0.831983
[100]	valid_0's multi_logloss: 0.821261
Did not meet early stopping. Best iteration is:
[100]	valid_0's multi_logloss: 0.821261


[I 2025-05-22 15:09:26,287] Trial 9 finished with value: 0.6520915212526802 and parameters: {'learning_rate': 0.015861327962547703, 'num_leaves': 234, 'max_depth': 16, 'min_child_samples': 41, 'subsample': 0.8466917503464884, 'colsample_bytree': 0.9802906474998063, 'reg_alpha': 3.2225941179084286e-07, 'reg_lambda': 0.31762541547494777}. Best is trial 4 with value: 0.6852568129546079.


Training until validation scores don't improve for 50 rounds
[10]	valid_0's multi_logloss: 0.846482
[20]	valid_0's multi_logloss: 0.785741
[30]	valid_0's multi_logloss: 0.759227
[40]	valid_0's multi_logloss: 0.743835
[50]	valid_0's multi_logloss: 0.733505
[60]	valid_0's multi_logloss: 0.726082
[70]	valid_0's multi_logloss: 0.720155
[80]	valid_0's multi_logloss: 0.715344
[90]	valid_0's multi_logloss: 0.711718
[100]	valid_0's multi_logloss: 0.708501
Did not meet early stopping. Best iteration is:
[100]	valid_0's multi_logloss: 0.708501


[I 2025-05-22 15:11:17,355] Trial 10 finished with value: 0.6882888308559739 and parameters: {'learning_rate': 0.13318215507905476, 'num_leaves': 182, 'max_depth': 8, 'min_child_samples': 13, 'subsample': 0.5192016835706874, 'colsample_bytree': 0.8893136963018567, 'reg_alpha': 7.731322898254129, 'reg_lambda': 8.97606796243808e-06}. Best is trial 10 with value: 0.6882888308559739.


Training until validation scores don't improve for 50 rounds
[10]	valid_0's multi_logloss: 0.794922
[20]	valid_0's multi_logloss: 0.754654
[30]	valid_0's multi_logloss: 0.737653
[40]	valid_0's multi_logloss: 0.727508
[50]	valid_0's multi_logloss: 0.720655
[60]	valid_0's multi_logloss: 0.715918
[70]	valid_0's multi_logloss: 0.711817
[80]	valid_0's multi_logloss: 0.708528
[90]	valid_0's multi_logloss: 0.705983
[100]	valid_0's multi_logloss: 0.703721
Did not meet early stopping. Best iteration is:
[100]	valid_0's multi_logloss: 0.703721


[I 2025-05-22 15:12:42,490] Trial 11 finished with value: 0.6899554023394302 and parameters: {'learning_rate': 0.2736763136325603, 'num_leaves': 187, 'max_depth': 7, 'min_child_samples': 10, 'subsample': 0.5045542044527518, 'colsample_bytree': 0.8965600150655003, 'reg_alpha': 9.538652695275518, 'reg_lambda': 9.979406380125947e-06}. Best is trial 11 with value: 0.6899554023394302.


Training until validation scores don't improve for 50 rounds
[10]	valid_0's multi_logloss: 0.866888
[20]	valid_0's multi_logloss: 0.801229
[30]	valid_0's multi_logloss: 0.77102
[40]	valid_0's multi_logloss: 0.753493
[50]	valid_0's multi_logloss: 0.741612
[60]	valid_0's multi_logloss: 0.733139
[70]	valid_0's multi_logloss: 0.726545
[80]	valid_0's multi_logloss: 0.721448
[90]	valid_0's multi_logloss: 0.717163
[100]	valid_0's multi_logloss: 0.713612
Did not meet early stopping. Best iteration is:
[100]	valid_0's multi_logloss: 0.713612


[I 2025-05-22 15:14:37,996] Trial 12 finished with value: 0.6862484489463219 and parameters: {'learning_rate': 0.10997475084568008, 'num_leaves': 174, 'max_depth': 8, 'min_child_samples': 10, 'subsample': 0.6333214248959615, 'colsample_bytree': 0.9907841937709034, 'reg_alpha': 6.449228285413934, 'reg_lambda': 6.3669311173826735e-06}. Best is trial 11 with value: 0.6899554023394302.


Training until validation scores don't improve for 50 rounds
[10]	valid_0's multi_logloss: 0.855448
[20]	valid_0's multi_logloss: 0.790949
[30]	valid_0's multi_logloss: 0.762167
[40]	valid_0's multi_logloss: 0.745264
[50]	valid_0's multi_logloss: 0.734152
[60]	valid_0's multi_logloss: 0.725876
[70]	valid_0's multi_logloss: 0.719355
[80]	valid_0's multi_logloss: 0.714134
[90]	valid_0's multi_logloss: 0.709829
[100]	valid_0's multi_logloss: 0.706224
Did not meet early stopping. Best iteration is:
[100]	valid_0's multi_logloss: 0.706224


[I 2025-05-22 15:16:58,517] Trial 13 finished with value: 0.6895452492329098 and parameters: {'learning_rate': 0.11882288413353986, 'num_leaves': 181, 'max_depth': 12, 'min_child_samples': 28, 'subsample': 0.6766061225295161, 'colsample_bytree': 0.8668902129806352, 'reg_alpha': 9.573501732709817, 'reg_lambda': 1.0615342171692177e-05}. Best is trial 11 with value: 0.6899554023394302.


Training until validation scores don't improve for 50 rounds
[10]	valid_0's multi_logloss: 0.902351
[20]	valid_0's multi_logloss: 0.82786
[30]	valid_0's multi_logloss: 0.790665
[40]	valid_0's multi_logloss: 0.768711
[50]	valid_0's multi_logloss: 0.753989
[60]	valid_0's multi_logloss: 0.74335
[70]	valid_0's multi_logloss: 0.735173
[80]	valid_0's multi_logloss: 0.728663
[90]	valid_0's multi_logloss: 0.723332
[100]	valid_0's multi_logloss: 0.718747
Did not meet early stopping. Best iteration is:
[100]	valid_0's multi_logloss: 0.718747


[I 2025-05-22 15:19:32,121] Trial 14 finished with value: 0.6835538987908271 and parameters: {'learning_rate': 0.07616348778321982, 'num_leaves': 198, 'max_depth': 12, 'min_child_samples': 30, 'subsample': 0.6570704587254748, 'colsample_bytree': 0.8131253529747628, 'reg_alpha': 0.35850771067531034, 'reg_lambda': 1.0708501185342604e-08}. Best is trial 11 with value: 0.6899554023394302.


Training until validation scores don't improve for 50 rounds
[10]	valid_0's multi_logloss: 0.9766
[20]	valid_0's multi_logloss: 0.90779
[30]	valid_0's multi_logloss: 0.864559
[40]	valid_0's multi_logloss: 0.835347
[50]	valid_0's multi_logloss: 0.8146
[60]	valid_0's multi_logloss: 0.799106
[70]	valid_0's multi_logloss: 0.787072
[80]	valid_0's multi_logloss: 0.77741
[90]	valid_0's multi_logloss: 0.769516
[100]	valid_0's multi_logloss: 0.762761
Did not meet early stopping. Best iteration is:
[100]	valid_0's multi_logloss: 0.762761


[I 2025-05-22 15:21:26,318] Trial 15 finished with value: 0.6641105648171703 and parameters: {'learning_rate': 0.04010737822006402, 'num_leaves': 101, 'max_depth': 12, 'min_child_samples': 29, 'subsample': 0.6931649802040128, 'colsample_bytree': 0.936980596020969, 'reg_alpha': 0.3034184024879293, 'reg_lambda': 1.8447772303959477e-05}. Best is trial 11 with value: 0.6899554023394302.


Training until validation scores don't improve for 50 rounds
[10]	valid_0's multi_logloss: 0.817885
[20]	valid_0's multi_logloss: 0.765337
[30]	valid_0's multi_logloss: 0.742774
[40]	valid_0's multi_logloss: 0.729741
[50]	valid_0's multi_logloss: 0.720813
[60]	valid_0's multi_logloss: 0.714185
[70]	valid_0's multi_logloss: 0.70932
[80]	valid_0's multi_logloss: 0.705327
[90]	valid_0's multi_logloss: 0.702302
[100]	valid_0's multi_logloss: 0.699634
Did not meet early stopping. Best iteration is:
[100]	valid_0's multi_logloss: 0.699634


[I 2025-05-22 15:23:29,104] Trial 16 finished with value: 0.692738213289999 and parameters: {'learning_rate': 0.17696581518849255, 'num_leaves': 150, 'max_depth': 11, 'min_child_samples': 30, 'subsample': 0.7729845912315098, 'colsample_bytree': 0.8058082817698655, 'reg_alpha': 0.4397040593821415, 'reg_lambda': 5.034537900836039e-07}. Best is trial 16 with value: 0.692738213289999.


Training until validation scores don't improve for 50 rounds
[10]	valid_0's multi_logloss: 1.08082
[20]	valid_0's multi_logloss: 1.06477
[30]	valid_0's multi_logloss: 1.04973
[40]	valid_0's multi_logloss: 1.03571
[50]	valid_0's multi_logloss: 1.02259
[60]	valid_0's multi_logloss: 1.01034
[70]	valid_0's multi_logloss: 0.998843
[80]	valid_0's multi_logloss: 0.988065
[90]	valid_0's multi_logloss: 0.977885
[100]	valid_0's multi_logloss: 0.968338
Did not meet early stopping. Best iteration is:
[100]	valid_0's multi_logloss: 0.968338


[I 2025-05-22 15:25:18,968] Trial 17 finished with value: 0.6280482423122251 and parameters: {'learning_rate': 0.004467503018101158, 'num_leaves': 102, 'max_depth': 10, 'min_child_samples': 22, 'subsample': 0.7761594257026669, 'colsample_bytree': 0.8064790131208445, 'reg_alpha': 0.2956310791092284, 'reg_lambda': 4.1058065924413234e-07}. Best is trial 16 with value: 0.692738213289999.


Training until validation scores don't improve for 50 rounds
[10]	valid_0's multi_logloss: 0.820254
[20]	valid_0's multi_logloss: 0.770646
[30]	valid_0's multi_logloss: 0.748936
[40]	valid_0's multi_logloss: 0.736436
[50]	valid_0's multi_logloss: 0.727885
[60]	valid_0's multi_logloss: 0.721474
[70]	valid_0's multi_logloss: 0.716554
[80]	valid_0's multi_logloss: 0.712754
[90]	valid_0's multi_logloss: 0.709762
[100]	valid_0's multi_logloss: 0.706943
Did not meet early stopping. Best iteration is:
[100]	valid_0's multi_logloss: 0.706943


[I 2025-05-22 15:26:41,109] Trial 18 finished with value: 0.6895192901755351 and parameters: {'learning_rate': 0.19592927706080487, 'num_leaves': 152, 'max_depth': 7, 'min_child_samples': 41, 'subsample': 0.8067940988350515, 'colsample_bytree': 0.6064193071550553, 'reg_alpha': 0.03807467624941193, 'reg_lambda': 2.883556524898922e-07}. Best is trial 16 with value: 0.692738213289999.


Training until validation scores don't improve for 50 rounds
[10]	valid_0's multi_logloss: 0.935559
[20]	valid_0's multi_logloss: 0.860915
[30]	valid_0's multi_logloss: 0.819747
[40]	valid_0's multi_logloss: 0.794208
[50]	valid_0's multi_logloss: 0.776872
[60]	valid_0's multi_logloss: 0.764164
[70]	valid_0's multi_logloss: 0.754431
[80]	valid_0's multi_logloss: 0.746647
[90]	valid_0's multi_logloss: 0.740265
[100]	valid_0's multi_logloss: 0.734976
Did not meet early stopping. Best iteration is:
[100]	valid_0's multi_logloss: 0.734976


[I 2025-05-22 15:29:02,791] Trial 19 finished with value: 0.6760257721521616 and parameters: {'learning_rate': 0.05786680511810161, 'num_leaves': 153, 'max_depth': 16, 'min_child_samples': 20, 'subsample': 0.6031250321323862, 'colsample_bytree': 0.9322006050177567, 'reg_alpha': 0.9603331432367691, 'reg_lambda': 0.0002339453974685718}. Best is trial 16 with value: 0.692738213289999.


Training until validation scores don't improve for 50 rounds
[10]	valid_0's multi_logloss: 1.07595
[20]	valid_0's multi_logloss: 1.05581
[30]	valid_0's multi_logloss: 1.03734
[40]	valid_0's multi_logloss: 1.0204
[50]	valid_0's multi_logloss: 1.00479
[60]	valid_0's multi_logloss: 0.990473
[70]	valid_0's multi_logloss: 0.977206
[80]	valid_0's multi_logloss: 0.964926
[90]	valid_0's multi_logloss: 0.953487
[100]	valid_0's multi_logloss: 0.942898
Did not meet early stopping. Best iteration is:
[100]	valid_0's multi_logloss: 0.942898


[I 2025-05-22 15:30:58,141] Trial 20 finished with value: 0.6329389287216203 and parameters: {'learning_rate': 0.005684020041776192, 'num_leaves': 119, 'max_depth': 10, 'min_child_samples': 37, 'subsample': 0.7099077133685512, 'colsample_bytree': 0.7933939200657499, 'reg_alpha': 0.03587155773460768, 'reg_lambda': 1.7161313836493476e-08}. Best is trial 16 with value: 0.692738213289999.


Training until validation scores don't improve for 50 rounds
[10]	valid_0's multi_logloss: 0.830055
[20]	valid_0's multi_logloss: 0.772596
[30]	valid_0's multi_logloss: 0.747638
[40]	valid_0's multi_logloss: 0.733308
[50]	valid_0's multi_logloss: 0.723677
[60]	valid_0's multi_logloss: 0.716479
[70]	valid_0's multi_logloss: 0.710971
[80]	valid_0's multi_logloss: 0.706497
[90]	valid_0's multi_logloss: 0.70297
[100]	valid_0's multi_logloss: 0.700023
Did not meet early stopping. Best iteration is:
[100]	valid_0's multi_logloss: 0.700023


[I 2025-05-22 15:33:23,935] Trial 21 finished with value: 0.6929874202407962 and parameters: {'learning_rate': 0.14892946295442894, 'num_leaves': 200, 'max_depth': 11, 'min_child_samples': 26, 'subsample': 0.7172909789705599, 'colsample_bytree': 0.9131774472721759, 'reg_alpha': 8.756226248115594, 'reg_lambda': 2.9636123400195476e-06}. Best is trial 21 with value: 0.6929874202407962.


Training until validation scores don't improve for 50 rounds
[10]	valid_0's multi_logloss: 0.800156
[20]	valid_0's multi_logloss: 0.752712
[30]	valid_0's multi_logloss: 0.732282
[40]	valid_0's multi_logloss: 0.720312
[50]	valid_0's multi_logloss: 0.712231
[60]	valid_0's multi_logloss: 0.706468
[70]	valid_0's multi_logloss: 0.702011
[80]	valid_0's multi_logloss: 0.698774
[90]	valid_0's multi_logloss: 0.69608
[100]	valid_0's multi_logloss: 0.693851
Did not meet early stopping. Best iteration is:
[100]	valid_0's multi_logloss: 0.693851


[I 2025-05-22 15:36:02,320] Trial 22 finished with value: 0.6952458582323958 and parameters: {'learning_rate': 0.20332043574295589, 'num_leaves': 204, 'max_depth': 14, 'min_child_samples': 20, 'subsample': 0.7265932795227208, 'colsample_bytree': 0.921095547587383, 'reg_alpha': 1.5769435974963355, 'reg_lambda': 1.5054183834739337e-06}. Best is trial 22 with value: 0.6952458582323958.


Training until validation scores don't improve for 50 rounds
[10]	valid_0's multi_logloss: 0.820141
[20]	valid_0's multi_logloss: 0.765065
[30]	valid_0's multi_logloss: 0.741456
[40]	valid_0's multi_logloss: 0.727619
[50]	valid_0's multi_logloss: 0.718582
[60]	valid_0's multi_logloss: 0.711815
[70]	valid_0's multi_logloss: 0.706592
[80]	valid_0's multi_logloss: 0.702517
[90]	valid_0's multi_logloss: 0.699409
[100]	valid_0's multi_logloss: 0.696662
Did not meet early stopping. Best iteration is:
[100]	valid_0's multi_logloss: 0.696662


[I 2025-05-22 15:38:45,163] Trial 23 finished with value: 0.6939686726095602 and parameters: {'learning_rate': 0.1621440835863917, 'num_leaves': 206, 'max_depth': 14, 'min_child_samples': 35, 'subsample': 0.744037851402626, 'colsample_bytree': 0.9399525760671057, 'reg_alpha': 1.1325961210027542, 'reg_lambda': 1.340005362773042e-06}. Best is trial 22 with value: 0.6952458582323958.


Training until validation scores don't improve for 50 rounds
[10]	valid_0's multi_logloss: 0.969622
[20]	valid_0's multi_logloss: 0.897782
[30]	valid_0's multi_logloss: 0.853022
[40]	valid_0's multi_logloss: 0.823053
[50]	valid_0's multi_logloss: 0.801959
[60]	valid_0's multi_logloss: 0.786322
[70]	valid_0's multi_logloss: 0.774239
[80]	valid_0's multi_logloss: 0.764604
[90]	valid_0's multi_logloss: 0.756617
[100]	valid_0's multi_logloss: 0.749898
Did not meet early stopping. Best iteration is:
[100]	valid_0's multi_logloss: 0.749898


[I 2025-05-22 15:41:38,258] Trial 24 finished with value: 0.6709066460378691 and parameters: {'learning_rate': 0.039650109974753336, 'num_leaves': 209, 'max_depth': 14, 'min_child_samples': 19, 'subsample': 0.7216861314671146, 'colsample_bytree': 0.943643212134292, 'reg_alpha': 1.3907725567076736, 'reg_lambda': 1.6477327105069553e-06}. Best is trial 22 with value: 0.6952458582323958.


Training until validation scores don't improve for 50 rounds
[10]	valid_0's multi_logloss: 0.827577
[20]	valid_0's multi_logloss: 0.769983
[30]	valid_0's multi_logloss: 0.745169
[40]	valid_0's multi_logloss: 0.73094
[50]	valid_0's multi_logloss: 0.721279
[60]	valid_0's multi_logloss: 0.714353
[70]	valid_0's multi_logloss: 0.708817
[80]	valid_0's multi_logloss: 0.704474
[90]	valid_0's multi_logloss: 0.701237
[100]	valid_0's multi_logloss: 0.698369
Did not meet early stopping. Best iteration is:
[100]	valid_0's multi_logloss: 0.698369


[I 2025-05-22 15:44:22,524] Trial 25 finished with value: 0.6929874202407962 and parameters: {'learning_rate': 0.1501064855531445, 'num_leaves': 206, 'max_depth': 15, 'min_child_samples': 37, 'subsample': 0.7311921980163155, 'colsample_bytree': 0.9623038251416486, 'reg_alpha': 0.07601649119429385, 'reg_lambda': 8.567038830775337e-05}. Best is trial 22 with value: 0.6952458582323958.


Training until validation scores don't improve for 50 rounds
[10]	valid_0's multi_logloss: 0.938069
[20]	valid_0's multi_logloss: 0.862254
[30]	valid_0's multi_logloss: 0.819717
[40]	valid_0's multi_logloss: 0.793172
[50]	valid_0's multi_logloss: 0.775152
[60]	valid_0's multi_logloss: 0.762087
[70]	valid_0's multi_logloss: 0.751955
[80]	valid_0's multi_logloss: 0.744016
[90]	valid_0's multi_logloss: 0.737554
[100]	valid_0's multi_logloss: 0.732011
Did not meet early stopping. Best iteration is:
[100]	valid_0's multi_logloss: 0.732011


[I 2025-05-22 15:47:13,079] Trial 26 finished with value: 0.6776092746520188 and parameters: {'learning_rate': 0.05396433856810172, 'num_leaves': 220, 'max_depth': 14, 'min_child_samples': 24, 'subsample': 0.7973813563393158, 'colsample_bytree': 0.9200770264898431, 'reg_alpha': 0.0034048321360300874, 'reg_lambda': 7.608898995951825e-08}. Best is trial 22 with value: 0.6952458582323958.


Training until validation scores don't improve for 50 rounds
[10]	valid_0's multi_logloss: 0.89141
[20]	valid_0's multi_logloss: 0.816882
[30]	valid_0's multi_logloss: 0.781043
[40]	valid_0's multi_logloss: 0.759966
[50]	valid_0's multi_logloss: 0.745883
[60]	valid_0's multi_logloss: 0.735724
[70]	valid_0's multi_logloss: 0.727979
[80]	valid_0's multi_logloss: 0.721711
[90]	valid_0's multi_logloss: 0.716641
[100]	valid_0's multi_logloss: 0.712322
Did not meet early stopping. Best iteration is:
[100]	valid_0's multi_logloss: 0.712322


[I 2025-05-22 15:50:04,338] Trial 27 finished with value: 0.6867001365446418 and parameters: {'learning_rate': 0.08094249209380999, 'num_leaves': 256, 'max_depth': 13, 'min_child_samples': 100, 'subsample': 0.8286006275988708, 'colsample_bytree': 0.848248716325895, 'reg_alpha': 2.2739753435433414e-05, 'reg_lambda': 2.1102873791150453e-06}. Best is trial 22 with value: 0.6952458582323958.


Training until validation scores don't improve for 50 rounds
[10]	valid_0's multi_logloss: 0.82148
[20]	valid_0's multi_logloss: 0.767524
[30]	valid_0's multi_logloss: 0.744099
[40]	valid_0's multi_logloss: 0.730617
[50]	valid_0's multi_logloss: 0.721196
[60]	valid_0's multi_logloss: 0.714284
[70]	valid_0's multi_logloss: 0.709205
[80]	valid_0's multi_logloss: 0.704999
[90]	valid_0's multi_logloss: 0.701501
[100]	valid_0's multi_logloss: 0.698748
Did not meet early stopping. Best iteration is:
[100]	valid_0's multi_logloss: 0.698748


[I 2025-05-22 15:52:22,197] Trial 28 finished with value: 0.6932522026260183 and parameters: {'learning_rate': 0.1681492167986351, 'num_leaves': 162, 'max_depth': 15, 'min_child_samples': 48, 'subsample': 0.6250399434825185, 'colsample_bytree': 0.9071753212796285, 'reg_alpha': 2.1324875473201956, 'reg_lambda': 3.736664333365487e-05}. Best is trial 22 with value: 0.6952458582323958.


Training until validation scores don't improve for 50 rounds
[10]	valid_0's multi_logloss: 0.784144
[20]	valid_0's multi_logloss: 0.744036
[30]	valid_0's multi_logloss: 0.726629
[40]	valid_0's multi_logloss: 0.716476
[50]	valid_0's multi_logloss: 0.709746
[60]	valid_0's multi_logloss: 0.70504
[70]	valid_0's multi_logloss: 0.701808
[80]	valid_0's multi_logloss: 0.69969
[90]	valid_0's multi_logloss: 0.698691
[100]	valid_0's multi_logloss: 0.698061
Did not meet early stopping. Best iteration is:
[100]	valid_0's multi_logloss: 0.698061


[I 2025-05-22 15:54:35,911] Trial 29 finished with value: 0.6928108986506482 and parameters: {'learning_rate': 0.2656633737871981, 'num_leaves': 166, 'max_depth': 15, 'min_child_samples': 48, 'subsample': 0.6283161856037432, 'colsample_bytree': 0.9855842880218362, 'reg_alpha': 0.10896667235410508, 'reg_lambda': 0.001597067098638028}. Best is trial 22 with value: 0.6952458582323958.


Training until validation scores don't improve for 50 rounds
[10]	valid_0's multi_logloss: 1.09438
[20]	valid_0's multi_logloss: 1.09047
[30]	valid_0's multi_logloss: 1.08664
[40]	valid_0's multi_logloss: 1.08289
[50]	valid_0's multi_logloss: 1.0792
[60]	valid_0's multi_logloss: 1.0756
[70]	valid_0's multi_logloss: 1.07205
[80]	valid_0's multi_logloss: 1.06856
[90]	valid_0's multi_logloss: 1.06514
[100]	valid_0's multi_logloss: 1.06177
Did not meet early stopping. Best iteration is:
[100]	valid_0's multi_logloss: 1.06177


[I 2025-05-22 15:55:57,563] Trial 30 finished with value: 0.583964571078495 and parameters: {'learning_rate': 0.0010434217237111916, 'num_leaves': 52, 'max_depth': 15, 'min_child_samples': 49, 'subsample': 0.5869591740212716, 'colsample_bytree': 0.9567731529742661, 'reg_alpha': 0.006216523645037096, 'reg_lambda': 5.0982431816993344e-05}. Best is trial 22 with value: 0.6952458582323958.


Training until validation scores don't improve for 50 rounds
[10]	valid_0's multi_logloss: 0.777215
[20]	valid_0's multi_logloss: 0.73958
[30]	valid_0's multi_logloss: 0.723567
[40]	valid_0's multi_logloss: 0.714262
[50]	valid_0's multi_logloss: 0.707985
[60]	valid_0's multi_logloss: 0.703565
[70]	valid_0's multi_logloss: 0.700681
[80]	valid_0's multi_logloss: 0.69859
[90]	valid_0's multi_logloss: 0.69729
[100]	valid_0's multi_logloss: 0.696104
Did not meet early stopping. Best iteration is:
[100]	valid_0's multi_logloss: 0.696104


[I 2025-05-22 15:58:19,789] Trial 31 finished with value: 0.69398943985546 and parameters: {'learning_rate': 0.28381634451817656, 'num_leaves': 194, 'max_depth': 13, 'min_child_samples': 38, 'subsample': 0.7534545160492495, 'colsample_bytree': 0.9201005098324443, 'reg_alpha': 2.424747209528658, 'reg_lambda': 5.8476521121932945e-08}. Best is trial 22 with value: 0.6952458582323958.


Training until validation scores don't improve for 50 rounds
[10]	valid_0's multi_logloss: 0.776505
[20]	valid_0's multi_logloss: 0.739434
[30]	valid_0's multi_logloss: 0.723733
[40]	valid_0's multi_logloss: 0.714301
[50]	valid_0's multi_logloss: 0.70854
[60]	valid_0's multi_logloss: 0.704515
[70]	valid_0's multi_logloss: 0.701512
[80]	valid_0's multi_logloss: 0.699584
[90]	valid_0's multi_logloss: 0.698488
[100]	valid_0's multi_logloss: 0.69778
Did not meet early stopping. Best iteration is:
[100]	valid_0's multi_logloss: 0.69778


[I 2025-05-22 16:00:24,764] Trial 32 finished with value: 0.6931120237161948 and parameters: {'learning_rate': 0.2977277085290891, 'num_leaves': 165, 'max_depth': 13, 'min_child_samples': 38, 'subsample': 0.756594943744406, 'colsample_bytree': 0.8382706080671114, 'reg_alpha': 1.3172142296404754, 'reg_lambda': 6.200929768565587e-08}. Best is trial 22 with value: 0.6952458582323958.


Training until validation scores don't improve for 50 rounds
[10]	valid_0's multi_logloss: 0.804811
[20]	valid_0's multi_logloss: 0.755798
[30]	valid_0's multi_logloss: 0.734818
[40]	valid_0's multi_logloss: 0.722591
[50]	valid_0's multi_logloss: 0.714309
[60]	valid_0's multi_logloss: 0.708253
[70]	valid_0's multi_logloss: 0.703428
[80]	valid_0's multi_logloss: 0.699879
[90]	valid_0's multi_logloss: 0.697091
[100]	valid_0's multi_logloss: 0.69459
Did not meet early stopping. Best iteration is:
[100]	valid_0's multi_logloss: 0.69459


[I 2025-05-22 16:02:57,120] Trial 33 finished with value: 0.6945034291914792 and parameters: {'learning_rate': 0.19502970459077415, 'num_leaves': 195, 'max_depth': 16, 'min_child_samples': 44, 'subsample': 0.74951421350585, 'colsample_bytree': 0.9007823178836107, 'reg_alpha': 1.9530048571348764, 'reg_lambda': 9.819786826253725e-07}. Best is trial 22 with value: 0.6952458582323958.


Training until validation scores don't improve for 50 rounds
[10]	valid_0's multi_logloss: 0.876051
[20]	valid_0's multi_logloss: 0.805912
[30]	valid_0's multi_logloss: 0.773304
[40]	valid_0's multi_logloss: 0.754332
[50]	valid_0's multi_logloss: 0.741553
[60]	valid_0's multi_logloss: 0.73211
[70]	valid_0's multi_logloss: 0.725016
[80]	valid_0's multi_logloss: 0.719247
[90]	valid_0's multi_logloss: 0.7143
[100]	valid_0's multi_logloss: 0.710176
Did not meet early stopping. Best iteration is:
[100]	valid_0's multi_logloss: 0.710176


[I 2025-05-22 16:05:32,011] Trial 34 finished with value: 0.6876969643478306 and parameters: {'learning_rate': 0.09646727173268844, 'num_leaves': 194, 'max_depth': 16, 'min_child_samples': 34, 'subsample': 0.750021887925773, 'colsample_bytree': 0.8798408234028349, 'reg_alpha': 2.5912320574714665, 'reg_lambda': 4.5670911859614597e-08}. Best is trial 22 with value: 0.6952458582323958.


Training until validation scores don't improve for 50 rounds
[10]	valid_0's multi_logloss: 0.79723
[20]	valid_0's multi_logloss: 0.750543
[30]	valid_0's multi_logloss: 0.731058
[40]	valid_0's multi_logloss: 0.71949
[50]	valid_0's multi_logloss: 0.71183
[60]	valid_0's multi_logloss: 0.706334
[70]	valid_0's multi_logloss: 0.702363
[80]	valid_0's multi_logloss: 0.699189
[90]	valid_0's multi_logloss: 0.69674
[100]	valid_0's multi_logloss: 0.695008
Did not meet early stopping. Best iteration is:
[100]	valid_0's multi_logloss: 0.695008


[I 2025-05-22 16:08:00,202] Trial 35 finished with value: 0.6941088515193836 and parameters: {'learning_rate': 0.20866068962595444, 'num_leaves': 222, 'max_depth': 14, 'min_child_samples': 59, 'subsample': 0.6701173787549743, 'colsample_bytree': 0.7735543123037549, 'reg_alpha': 0.11625241537761884, 'reg_lambda': 8.841898814739074e-07}. Best is trial 22 with value: 0.6952458582323958.


Training until validation scores don't improve for 50 rounds
[10]	valid_0's multi_logloss: 0.99744
[20]	valid_0's multi_logloss: 0.932183
[30]	valid_0's multi_logloss: 0.886798
[40]	valid_0's multi_logloss: 0.854063
[50]	valid_0's multi_logloss: 0.829975
[60]	valid_0's multi_logloss: 0.811531
[70]	valid_0's multi_logloss: 0.797179
[80]	valid_0's multi_logloss: 0.785649
[90]	valid_0's multi_logloss: 0.776142
[100]	valid_0's multi_logloss: 0.76819
Did not meet early stopping. Best iteration is:
[100]	valid_0's multi_logloss: 0.76819


[I 2025-05-22 16:10:32,627] Trial 36 finished with value: 0.6664105373005695 and parameters: {'learning_rate': 0.029147047927054682, 'num_leaves': 242, 'max_depth': 13, 'min_child_samples': 58, 'subsample': 0.8016330384961625, 'colsample_bytree': 0.6282130198268223, 'reg_alpha': 0.002052818609222354, 'reg_lambda': 1.355683829491551e-07}. Best is trial 22 with value: 0.6952458582323958.


Training until validation scores don't improve for 50 rounds
[10]	valid_0's multi_logloss: 0.794394
[20]	valid_0's multi_logloss: 0.74854
[30]	valid_0's multi_logloss: 0.729448
[40]	valid_0's multi_logloss: 0.718396
[50]	valid_0's multi_logloss: 0.710859
[60]	valid_0's multi_logloss: 0.70544
[70]	valid_0's multi_logloss: 0.701585
[80]	valid_0's multi_logloss: 0.698356
[90]	valid_0's multi_logloss: 0.695846
[100]	valid_0's multi_logloss: 0.694381
Did not meet early stopping. Best iteration is:
[100]	valid_0's multi_logloss: 0.694381


[I 2025-05-22 16:12:56,768] Trial 37 finished with value: 0.6945916899865532 and parameters: {'learning_rate': 0.21669419605771448, 'num_leaves': 220, 'max_depth': 16, 'min_child_samples': 75, 'subsample': 0.6704220051869529, 'colsample_bytree': 0.7755543147553102, 'reg_alpha': 5.159391855166696e-05, 'reg_lambda': 7.040568919161277e-07}. Best is trial 22 with value: 0.6952458582323958.


Training until validation scores don't improve for 50 rounds
[10]	valid_0's multi_logloss: 1.05488
[20]	valid_0's multi_logloss: 1.01893
[30]	valid_0's multi_logloss: 0.988239
[40]	valid_0's multi_logloss: 0.96182
[50]	valid_0's multi_logloss: 0.939023
[60]	valid_0's multi_logloss: 0.919227
[70]	valid_0's multi_logloss: 0.90193
[80]	valid_0's multi_logloss: 0.886793
[90]	valid_0's multi_logloss: 0.873352
[100]	valid_0's multi_logloss: 0.861558
Did not meet early stopping. Best iteration is:
[100]	valid_0's multi_logloss: 0.861558


[I 2025-05-22 16:15:27,017] Trial 38 finished with value: 0.6495994517447082 and parameters: {'learning_rate': 0.011025337379325307, 'num_leaves': 222, 'max_depth': 16, 'min_child_samples': 73, 'subsample': 0.6679490827668636, 'colsample_bytree': 0.6728010419935233, 'reg_alpha': 4.2929313559727454e-05, 'reg_lambda': 7.042135518863523e-07}. Best is trial 22 with value: 0.6952458582323958.


Training until validation scores don't improve for 50 rounds
[10]	valid_0's multi_logloss: 0.789286
[20]	valid_0's multi_logloss: 0.74511
[30]	valid_0's multi_logloss: 0.726656
[40]	valid_0's multi_logloss: 0.715881
[50]	valid_0's multi_logloss: 0.708948
[60]	valid_0's multi_logloss: 0.704046
[70]	valid_0's multi_logloss: 0.700665
[80]	valid_0's multi_logloss: 0.697788
[90]	valid_0's multi_logloss: 0.695497
[100]	valid_0's multi_logloss: 0.694359
Did not meet early stopping. Best iteration is:
[100]	valid_0's multi_logloss: 0.694359


[I 2025-05-22 16:17:57,859] Trial 39 finished with value: 0.6952562418553457 and parameters: {'learning_rate': 0.2276235111540587, 'num_leaves': 242, 'max_depth': 15, 'min_child_samples': 76, 'subsample': 0.6919191976188034, 'colsample_bytree': 0.7695346874835, 'reg_alpha': 1.3446566777159403e-06, 'reg_lambda': 0.010913349156401042}. Best is trial 39 with value: 0.6952562418553457.


Training until validation scores don't improve for 50 rounds
[10]	valid_0's multi_logloss: 0.926401
[20]	valid_0's multi_logloss: 0.849462
[30]	valid_0's multi_logloss: 0.807943
[40]	valid_0's multi_logloss: 0.782759
[50]	valid_0's multi_logloss: 0.765999
[60]	valid_0's multi_logloss: 0.753626
[70]	valid_0's multi_logloss: 0.744268
[80]	valid_0's multi_logloss: 0.736801
[90]	valid_0's multi_logloss: 0.730576
[100]	valid_0's multi_logloss: 0.725433
Did not meet early stopping. Best iteration is:
[100]	valid_0's multi_logloss: 0.725433


[I 2025-05-22 16:20:43,650] Trial 40 finished with value: 0.6816744630368982 and parameters: {'learning_rate': 0.05985416516742102, 'num_leaves': 249, 'max_depth': 15, 'min_child_samples': 83, 'subsample': 0.6978768530144364, 'colsample_bytree': 0.7616570119036863, 'reg_alpha': 1.1774778147724144e-06, 'reg_lambda': 0.008201441176931855}. Best is trial 39 with value: 0.6952562418553457.


Training until validation scores don't improve for 50 rounds
[10]	valid_0's multi_logloss: 0.796554
[20]	valid_0's multi_logloss: 0.75005
[30]	valid_0's multi_logloss: 0.730373
[40]	valid_0's multi_logloss: 0.71901
[50]	valid_0's multi_logloss: 0.711462
[60]	valid_0's multi_logloss: 0.705967
[70]	valid_0's multi_logloss: 0.701927
[80]	valid_0's multi_logloss: 0.698824
[90]	valid_0's multi_logloss: 0.69638
[100]	valid_0's multi_logloss: 0.694583
Did not meet early stopping. Best iteration is:
[100]	valid_0's multi_logloss: 0.694583


[I 2025-05-22 16:23:10,634] Trial 41 finished with value: 0.6953756535192694 and parameters: {'learning_rate': 0.21062203597149756, 'num_leaves': 222, 'max_depth': 16, 'min_child_samples': 77, 'subsample': 0.6580912408833793, 'colsample_bytree': 0.7692238505371277, 'reg_alpha': 5.901408442631763e-08, 'reg_lambda': 0.0021466669288140797}. Best is trial 41 with value: 0.6953756535192694.


Training until validation scores don't improve for 50 rounds
[10]	valid_0's multi_logloss: 0.798247
[20]	valid_0's multi_logloss: 0.751031
[30]	valid_0's multi_logloss: 0.73123
[40]	valid_0's multi_logloss: 0.719661
[50]	valid_0's multi_logloss: 0.711859
[60]	valid_0's multi_logloss: 0.706556
[70]	valid_0's multi_logloss: 0.702351
[80]	valid_0's multi_logloss: 0.698866
[90]	valid_0's multi_logloss: 0.696581
[100]	valid_0's multi_logloss: 0.694923
Did not meet early stopping. Best iteration is:
[100]	valid_0's multi_logloss: 0.694923


[I 2025-05-22 16:25:49,757] Trial 42 finished with value: 0.6942957567324816 and parameters: {'learning_rate': 0.20501497237523228, 'num_leaves': 233, 'max_depth': 16, 'min_child_samples': 79, 'subsample': 0.643655222514944, 'colsample_bytree': 0.7266044030685062, 'reg_alpha': 4.200445235994374e-08, 'reg_lambda': 0.03219101292858958}. Best is trial 41 with value: 0.6953756535192694.


Training until validation scores don't improve for 50 rounds
[10]	valid_0's multi_logloss: 0.851381
[20]	valid_0's multi_logloss: 0.785368
[30]	valid_0's multi_logloss: 0.756424
[40]	valid_0's multi_logloss: 0.739795
[50]	valid_0's multi_logloss: 0.728631
[60]	valid_0's multi_logloss: 0.720433
[70]	valid_0's multi_logloss: 0.714118
[80]	valid_0's multi_logloss: 0.709199
[90]	valid_0's multi_logloss: 0.704831
[100]	valid_0's multi_logloss: 0.701297
Did not meet early stopping. Best iteration is:
[100]	valid_0's multi_logloss: 0.701297


[I 2025-05-22 16:28:36,401] Trial 43 finished with value: 0.6925201572080515 and parameters: {'learning_rate': 0.11751946001260129, 'num_leaves': 244, 'max_depth': 16, 'min_child_samples': 93, 'subsample': 0.5774299188634813, 'colsample_bytree': 0.6903109997304735, 'reg_alpha': 1.416041997519428e-07, 'reg_lambda': 0.004113161722515314}. Best is trial 41 with value: 0.6953756535192694.


Training until validation scores don't improve for 50 rounds
[10]	valid_0's multi_logloss: 0.789555
[20]	valid_0's multi_logloss: 0.745986
[30]	valid_0's multi_logloss: 0.727743
[40]	valid_0's multi_logloss: 0.717105
[50]	valid_0's multi_logloss: 0.710247
[60]	valid_0's multi_logloss: 0.705193
[70]	valid_0's multi_logloss: 0.701696
[80]	valid_0's multi_logloss: 0.698806
[90]	valid_0's multi_logloss: 0.696549
[100]	valid_0's multi_logloss: 0.69528
Did not meet early stopping. Best iteration is:
[100]	valid_0's multi_logloss: 0.69528


[I 2025-05-22 16:31:04,659] Trial 44 finished with value: 0.69488243142915 and parameters: {'learning_rate': 0.2324130421867477, 'num_leaves': 215, 'max_depth': 15, 'min_child_samples': 66, 'subsample': 0.9913735116297412, 'colsample_bytree': 0.7229164524299625, 'reg_alpha': 1.7526871585297524e-06, 'reg_lambda': 0.0008497191372820878}. Best is trial 41 with value: 0.6953756535192694.


Training until validation scores don't improve for 50 rounds
[10]	valid_0's multi_logloss: 0.79154
[20]	valid_0's multi_logloss: 0.747472
[30]	valid_0's multi_logloss: 0.728795
[40]	valid_0's multi_logloss: 0.717964
[50]	valid_0's multi_logloss: 0.710663
[60]	valid_0's multi_logloss: 0.705668
[70]	valid_0's multi_logloss: 0.701958
[80]	valid_0's multi_logloss: 0.699158
[90]	valid_0's multi_logloss: 0.697009
[100]	valid_0's multi_logloss: 0.695546
Did not meet early stopping. Best iteration is:
[100]	valid_0's multi_logloss: 0.695546


[I 2025-05-22 16:33:26,291] Trial 45 finished with value: 0.6941503860111832 and parameters: {'learning_rate': 0.22518173519489812, 'num_leaves': 215, 'max_depth': 15, 'min_child_samples': 66, 'subsample': 0.9911590078906589, 'colsample_bytree': 0.728154761062549, 'reg_alpha': 3.1834331784950308e-06, 'reg_lambda': 0.045075835718831204}. Best is trial 41 with value: 0.6953756535192694.


Training until validation scores don't improve for 50 rounds
[10]	valid_0's multi_logloss: 0.871609
[20]	valid_0's multi_logloss: 0.800947
[30]	valid_0's multi_logloss: 0.768838
[40]	valid_0's multi_logloss: 0.750137
[50]	valid_0's multi_logloss: 0.73761
[60]	valid_0's multi_logloss: 0.728567
[70]	valid_0's multi_logloss: 0.721703
[80]	valid_0's multi_logloss: 0.716054
[90]	valid_0's multi_logloss: 0.711379
[100]	valid_0's multi_logloss: 0.707553
Did not meet early stopping. Best iteration is:
[100]	valid_0's multi_logloss: 0.707553


[I 2025-05-22 16:35:50,881] Trial 46 finished with value: 0.689358344019812 and parameters: {'learning_rate': 0.09925043535179144, 'num_leaves': 232, 'max_depth': 14, 'min_child_samples': 72, 'subsample': 0.8902848621247501, 'colsample_bytree': 0.6259751137097704, 'reg_alpha': 3.874105984992348e-05, 'reg_lambda': 0.0011810957044216864}. Best is trial 41 with value: 0.6953756535192694.


Training until validation scores don't improve for 50 rounds
[10]	valid_0's multi_logloss: 0.825029
[20]	valid_0's multi_logloss: 0.779362
[30]	valid_0's multi_logloss: 0.759351
[40]	valid_0's multi_logloss: 0.74732
[50]	valid_0's multi_logloss: 0.738452
[60]	valid_0's multi_logloss: 0.732032
[70]	valid_0's multi_logloss: 0.726878
[80]	valid_0's multi_logloss: 0.722733
[90]	valid_0's multi_logloss: 0.719293
[100]	valid_0's multi_logloss: 0.71639
Did not meet early stopping. Best iteration is:
[100]	valid_0's multi_logloss: 0.71639


[I 2025-05-22 16:36:57,423] Trial 47 finished with value: 0.682936073225309 and parameters: {'learning_rate': 0.24154971452914184, 'num_leaves': 31, 'max_depth': 15, 'min_child_samples': 64, 'subsample': 0.6816183790461292, 'colsample_bytree': 0.7802754852885572, 'reg_alpha': 3.6332693482673153e-07, 'reg_lambda': 0.000623343294588864}. Best is trial 41 with value: 0.6953756535192694.


Training until validation scores don't improve for 50 rounds
[10]	valid_0's multi_logloss: 0.838512
[20]	valid_0's multi_logloss: 0.776996
[30]	valid_0's multi_logloss: 0.750311
[40]	valid_0's multi_logloss: 0.735032
[50]	valid_0's multi_logloss: 0.724851
[60]	valid_0's multi_logloss: 0.717324
[70]	valid_0's multi_logloss: 0.711391
[80]	valid_0's multi_logloss: 0.706704
[90]	valid_0's multi_logloss: 0.702829
[100]	valid_0's multi_logloss: 0.699703
Did not meet early stopping. Best iteration is:
[100]	valid_0's multi_logloss: 0.699703


[I 2025-05-22 16:39:24,245] Trial 48 finished with value: 0.6931899008883189 and parameters: {'learning_rate': 0.13453638966299902, 'num_leaves': 224, 'max_depth': 14, 'min_child_samples': 80, 'subsample': 0.6477607347218769, 'colsample_bytree': 0.7121131519039022, 'reg_alpha': 9.586184155172608e-06, 'reg_lambda': 0.02393163876880972}. Best is trial 41 with value: 0.6953756535192694.


Training until validation scores don't improve for 50 rounds
[10]	valid_0's multi_logloss: 0.906501
[20]	valid_0's multi_logloss: 0.830254
[30]	valid_0's multi_logloss: 0.791965
[40]	valid_0's multi_logloss: 0.769216
[50]	valid_0's multi_logloss: 0.754089
[60]	valid_0's multi_logloss: 0.743103
[70]	valid_0's multi_logloss: 0.734612
[80]	valid_0's multi_logloss: 0.72792
[90]	valid_0's multi_logloss: 0.722334
[100]	valid_0's multi_logloss: 0.71763
Did not meet early stopping. Best iteration is:
[100]	valid_0's multi_logloss: 0.71763


[I 2025-05-22 16:42:07,399] Trial 49 finished with value: 0.6842080670366698 and parameters: {'learning_rate': 0.07167478158522553, 'num_leaves': 244, 'max_depth': 15, 'min_child_samples': 76, 'subsample': 0.5572078701737916, 'colsample_bytree': 0.7492229241104136, 'reg_alpha': 0.00011602969017084999, 'reg_lambda': 0.0001564256909356638}. Best is trial 41 with value: 0.6953756535192694.


✅ Best LightGBM params: {'learning_rate': 0.21062203597149756, 'num_leaves': 222, 'max_depth': 16, 'min_child_samples': 77, 'subsample': 0.6580912408833793, 'colsample_bytree': 0.7692238505371277, 'reg_alpha': 5.901408442631763e-08, 'reg_lambda': 0.0021466669288140797}
Training until validation scores don't improve for 50 rounds
[10]	valid_0's multi_logloss: 0.796554
[20]	valid_0's multi_logloss: 0.75005
[30]	valid_0's multi_logloss: 0.730373
[40]	valid_0's multi_logloss: 0.719009
[50]	valid_0's multi_logloss: 0.711462
[60]	valid_0's multi_logloss: 0.705967
[70]	valid_0's multi_logloss: 0.701927
[80]	valid_0's multi_logloss: 0.698823
[90]	valid_0's multi_logloss: 0.696379
[100]	valid_0's multi_logloss: 0.694583
Did not meet early stopping. Best iteration is:
[100]	valid_0's multi_logloss: 0.694583
✅ LightGBM model saved to best_lightgbm.pkl


### Xgboost hyper-parameter tuning

In [ ]:
# XGBOOST OPTUNA TUNING + SAVE
# -------------------------------
def objective_xgb(trial):
    param = {
        'objective': 'multi:softprob',
        'eval_metric': 'mlogloss',
        'num_class': len(set(y)),
        'tree_method': 'gpu_hist',
        'learning_rate': trial.suggest_float('learning_rate', 1e-3, 0.3, log=True),
        'max_depth': trial.suggest_int('max_depth', 3, 15),
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 10),
        'gamma': trial.suggest_float('gamma', 0, 5),
        'subsample': trial.suggest_float('subsample', 0.5, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.5, 1.0),
        'lambda': trial.suggest_float('lambda', 1e-8, 10.0, log=True),
        'alpha': trial.suggest_float('alpha', 1e-8, 10.0, log=True)
    }

    model = xgb.XGBClassifier(
        **param,
        use_label_encoder=False,
        random_state=42,
    )

    model.set_params(early_stopping_rounds=50)
    model.fit(
        X_train, y_train,
        eval_set=[(X_val, y_val)],
        verbose=False
    )

    preds = model.predict(X_val)
    return accuracy_score(y_val, preds)

# Run XGBoost tuning
study_xgb = optuna.create_study(direction='maximize')
study_xgb.optimize(objective_xgb, n_trials=50)
print("✅ Best XGBoost params:", study_xgb.best_params)

# Train final XGBoost model with best params
best_params_xgb = study_xgb.best_params
best_params_xgb.update({
    'objective': 'multi:softprob',
    'eval_metric': 'mlogloss',
    'num_class': len(set(y)),
    'tree_method': 'gpu_hist',
    'use_label_encoder': False,
    'random_state': 42
})

final_xgb = xgb.XGBClassifier(**best_params_xgb)
final_xgb.fit(
    X_train, y_train,
    eval_set=[(X_val, y_val)],
    early_stopping_rounds=50,
    verbose=False
)

# Save final XGBoost model
joblib.dump(final_xgb, 'best_xgboost.pkl')
print("✅ XGBoost model saved to best_xgboost.pkl")

[I 2025-05-22 16:47:33,663] A new study created in memory with name: no-name-85b8f5bc-753c-40e6-93ec-d825c9560a3a
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [16:48:07] WARNING: /workspace/src/common/error_msg.cc:27: The tree method `gpu_hist` is deprecated since 2.0.0. To use GPU training, set the `device` parameter to CUDA instead.

    E.g. tree_method = "hist", device = "cuda"

  warnings.warn(smsg, UserWarning)
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [16:48:07] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [16:48:20] WARNING: /workspace/src/common/error_msg.cc:27: The tree method `gpu_hist` is deprecated since 2.0.0. To use GPU training, set the `device` parameter to CUDA instead.

    E.g. tree_method = "hist", device = "cuda"

  warnings.warn(smsg, UserWarning)
/u